### ISSUE TITLE
Issue more current release

### ISSUE THREAD

**Issue by ghost** [vue-bulma/chartjs#5]
Hey there!

Nice project, I greatly appreciate the Vue 2 support!
However, can you please release a more current version than 1.0.0, so it's installable via npm? 

Thanks a lot!

**Comment by vernard** [comment]
There was a temporary solution provided in #7 

> so I modify my package.json > dependencies like this:
> "vue-bulma-chartjs": "git+https://github.com/vue-bulma/chartjs.git"
> And run `npm install vue-bulma-chartjs`
