### ISSUE TITLE
Module not found: Error: Can't resolve 'scss-loader'

### ISSUE THREAD

**Issue by wxs77577** [vue-bulma/chartjs#6]
I just use `npm install vue-bulma-chartjs` and got some errors
```
ERROR in ./~/vue-bulma-chartjs/src/Chartjs.vue
Module not found: Error: Can't resolve 'scss-loader' in '/Library/WebServer/Documents/vue/node_modules/vue-bulma-chartjs/src'
 @ ./~/vue-bulma-chartjs/src/Chartjs.vue 5:0-159
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi main
````

**Comment by pepzwee** [comment]
+1, same issue

**Comment by wxs77577** [comment]
I have solved this problem.
1. change `webpack.config.js` > `module` > `rules` > `vue` section
```javascript
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            scss: 'style-loader!css-loader!sass-loader'
          }
          // vue-loader options go here
        }
      },
```
2. `npm install style-loader css-loader sass-loader --save-dev`
3.  run `webpack` or `npm run dev`

**Comment by wxs77577** [comment]
Reference to: 
* [https://github.com/jtangelder/sass-loader#apply-via-webpack-config](https://github.com/jtangelder/sass-loader#apply-via-webpack-config)
* [http://vue-loader.vuejs.org/en/configurations/advanced.html](http://vue-loader.vuejs.org/en/configurations/advanced.html) > `Webpack 2.x`
